kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-web-svc
  labels:
    app: {{ .Values.app_name }}
    tier: web
    environment: {{ .Values.site_environment }}
spec:
  selector:
    app: {{ .Values.app_name }}
    tier: web
    environment: {{ .Values.site_environment }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80